# Generated by Django 3.0.8 on 2020-09-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lerntag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('zeit_arbeit_mental', models.DecimalField(decimal_places=1, max_digits=3)),
                ('zeit_arbeit_shallow', models.DecimalField(decimal_places=1, max_digits=3)),
                ('zeit_freizeit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('zeit_organisation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('output_productivity', models.PositiveIntegerField()),
                ('output_happiness', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lerntag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
