# Generated by Django 2.2.7 on 2020-08-13 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lerntag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.date(2020, 8, 13))),
                ('notiz', models.TextField(blank=True, null=True)),
                ('zeit_lernen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zeit_freizeit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zeit_freundin', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
