# Generated by Django 3.0.8 on 2020-08-15 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input_lerntag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerntag',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
