# Generated by Django 3.0.8 on 2020-09-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_lerntag', '0002_auto_20200815_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lerntag',
            name='notiz',
        ),
        migrations.RemoveField(
            model_name='lerntag',
            name='zeit_freundin',
        ),
        migrations.RemoveField(
            model_name='lerntag',
            name='zeit_lernen',
        ),
        migrations.AddField(
            model_name='lerntag',
            name='zeit_arbeit_mental',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lerntag',
            name='zeit_arbeit_shallow',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lerntag',
            name='zeit_organisation',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lerntag',
            name='zeit_freizeit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
