# Generated by Django 3.0.8 on 2020-09-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_lerntag', '0003_auto_20200907_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerntag',
            name='zeit_arbeit_mental',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lerntag',
            name='zeit_arbeit_shallow',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lerntag',
            name='zeit_freizeit',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lerntag',
            name='zeit_organisation',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
