# Generated by Django 3.0.8 on 2020-09-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_lerntag', '0004_auto_20200911_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerntag',
            name='output_happiness',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lerntag',
            name='output_productivity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
