# Generated by Django 3.0.8 on 2020-09-14 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input_lerntag', '0007_auto_20200915_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerntag',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
