# Generated by Django 3.0.8 on 2020-09-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input_lerntag', '0008_auto_20200915_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lerntag',
            name='student',
        ),
        migrations.AddField(
            model_name='lerntag',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lerntag', to=settings.AUTH_USER_MODEL),
        ),
    ]
