# Generated by Django 3.0.8 on 2020-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('DW', 'Deepwork'), ('SW', 'Shallow Work'), ('fz', 'Freizeit'), ('org', 'Organisation')], default='SW', max_length=3),
        ),
    ]
