# Generated by Django 3.0.8 on 2020-09-14 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0002_auto_20200914_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 2, 22, 22, 283814), null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('DW', 'Deepwork'), ('SW', 'Shallow Work'), ('FZ', 'Freizeit'), ('ORG', 'Organisation')], default='SW', max_length=3),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 0, 22, 22, 283814), null=True),
        ),
    ]
