# Generated by Django 3.0.8 on 2020-09-20 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fullcalendar', '0006_auto_20200918_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Besitzer',
        ),
        migrations.AddField(
            model_name='events',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 20, 15, 11, 57, 244477), null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 20, 13, 11, 57, 244477), null=True),
        ),
    ]
