# Generated by Django 3.0.8 on 2020-09-21 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0015_auto_20200921_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 9, 30, 18, 111026)),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 7, 30, 18, 111026)),
        ),
    ]
